### ISSUE TITLE
typo in cache directory line

### ISSUE THREAD

**Issue by raylee** [stormforger/example-github-actions#17]
Hi there,

I randomly landed on this repo when looking for an example, and I noticed a typo that you'll probably want to address (s/hone/home/):

https://github.com/stormforger/example-github-actions/blob/31fd3d0a7df0d9a9260b3c875374b8c6d969629e/.github/workflows/cicd.yml#L27

**Comment by zeisss** [comment]
Oh yeah, thanks for pointing this out. Will fix ASAP.
